apiVersion: v1
kind: Pod
metadata:
  name: test-secret-env-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.37
      command: ["/bin/sh", "-c", "env"]
      envFrom:
      - secretRef:
          name: test-secret
  restartPolicy: Never
