apiVersion: v1
kind: Pod
metadata:
  name: test-configmap-volume-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.37
      command: ["/bin/sh", "-c", "ls /etc/config/"]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: test-configmap
  restartPolicy: Never
