apiVersion: v1
kind: Pod
metadata:
  name: test-configmap-env-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.37
      command: ["/bin/echo", "$(CONFIG_LEVEL) $(CONFIG_TYPE)"]
      env:
        - name: CONFIG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: config_level
        - name: CONFIG_TYPE
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: config_type
  restartPolicy: Never
